backend:
  name: git-gateway
  branch: master

media-folder: static/images
public_folder: ../../static/images/

collections:
  - name: "travel-packages"
    preview: false
    label: "Travel Packages"
    folder: "content/travel-packages"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Location", name: "location", widget: "string"}
      - { label: "Travel Dates", name: "travel-dates", widget: "string"}
      - { label: "Featured Image", name: "featured-image", widget: "image"}
      - { label: "Body", name" "body", widget: "markdown"}npm 